In [1]:
import os
import numpy as np
import pandas as pd

The history saving thread hit an unexpected error (DatabaseError('database disk image is malformed')).History will not be written to the database.


In [2]:
os.chdir("/cellar/users/aklie/data/datasets/King20_OSKN_MPRA/")

In [3]:
from bin.King20 import king20, tfbs_encode, ResidualBind

OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.


In [4]:
data = king20("SYN", "./processed/2024_03_10")
data = data[data["Element_id"] != "Basal"]
data

Design spreadsheet already exists at ./design.xlsx
Model spreadsheet already exists at ./models.xlsx


Barcode             Element_id  \
0    AAACACTTG  Or-Kr-Er-Sf_synthetic   
1    AAACCAAGT        Er-Or_synthetic   
2    AAACCACAA  Or-Sr-Kf-Er_synthetic   
3    AAACCAGAC  Kf-Er-Sr-Of_synthetic   
4    AAACCAGTG  Kr-Sf-Ef-Or_synthetic   
..         ...                    ...   
632  CTCCTAAAG  Sr-Kf-Ef-Of_synthetic   
633  CTGGGTACC     Sr-Ef-Kf_synthetic   
634  CTTCGTCCC     Kr-Sf-Or_synthetic   
635  GAGAGCGGA        Er-Sf_synthetic   
636  GAGGTTAGC  Er-Of-Sr-Kr_synthetic   

                                              Sequence Element_id_simplified  \
0    AGCTACGATTAGCATCCCGTAGCTAGCGGCCCCACCCCGTAGCTAC...                  okeS   
1             AGCTACGTGACCTTGAACGTAGCTACGATTAGCATCCCGT                    eo   
2    AGCTACGATTAGCATCCCGTAGCTACGAAACAATGAGCGTAGCTAC...                  osKe   
3    AGCTACGGGGTGGGGCCGCTAGCTACGTGACCTTGAACGTAGCTAC...                  KesO   
4    AGCTAGCGGCCCCACCCCGTAGCTACGCTCATTGTTTCGTAGCTAC...                  kSEo   
..                                                 ...                   ...   
632  AGCTACGAAACAATGAGCGTAGCTACGGGGTGGGGCCGCTAGCTAC...                  sKEO   
633  AGCTACGAAACAATGAGCGTAGCTACGTTCAAGGTCACGTAGCTAC...                   sEK   
634  AGCTAGCGGCCCCACCCCGTAGCTACGCTCATTGTTTCGTAGCTAC...                   kSo   
635           AGCTACGTGACCTTGAACGTAGCTACGCTCATTGTTTCGT                    eS   
636  AGCTACGTGACCTTGAACGTAGCTACGGGATGCTAATCGTAGCTAC...                  eOsk   

    Class  CRE_normalized_mean O_presence S_presence K_presence E_presence  \
0    4mer             4.589322       True       True       True       True   
1    2mer             1.008053       True      False      False       True   
2    4mer            10.712129       True       True       True       True   
3    4mer             3.453898       True       True       True       True   
4    4mer             3.939580       True       True       True       True   
..    ...                  ...        ...        ...        ...        ...   
632  4mer             6.241055       True       True       True       True   
633  3mer             3.106084      False       True       True       True   
634  3mer             2.145780       True       True       True      False   
635  2mer             1.003107      False       True      False       True   
636  4mer             4.307021       True       True       True       True   

     ... Position.3_K Position.3_E Position.2_O Position.2_S Position.2_K  \
0    ...        False         True        False        False         True   
1    ...        False         True        False        False        False   
2    ...         True        False        False         True        False   
3    ...        False        False        False        False        False   
4    ...        False         True        False         True        False   
..   ...          ...          ...          ...          ...          ...   
632  ...        False         True        False        False         True   
633  ...        False         True        False         True        False   
634  ...        False        False        False        False         True   
635  ...        False         True        False        False        False   
636  ...        False        False         True        False        False   

    Position.2_E Position.1_O Position.1_S Position.1_K Position.1_E  
0          False         True        False        False        False  
1          False        False        False        False        False  
2          False         True        False        False        False  
3           True        False        False         True        False  
4          False        False        False         True        False  
..           ...          ...          ...          ...          ...  
632        False        False         True        False        False  
633        False        False        False        False        False  
634        False        False        False        Fa

In [5]:
# Check for NaNs in "Sequence" and remove them
data["Sequence"].isna().sum()
data = data.dropna(subset=["Sequence"])
data

Barcode             Element_id  \
0    AAACACTTG  Or-Kr-Er-Sf_synthetic   
1    AAACCAAGT        Er-Or_synthetic   
2    AAACCACAA  Or-Sr-Kf-Er_synthetic   
3    AAACCAGAC  Kf-Er-Sr-Of_synthetic   
4    AAACCAGTG  Kr-Sf-Ef-Or_synthetic   
..         ...                    ...   
632  CTCCTAAAG  Sr-Kf-Ef-Of_synthetic   
633  CTGGGTACC     Sr-Ef-Kf_synthetic   
634  CTTCGTCCC     Kr-Sf-Or_synthetic   
635  GAGAGCGGA        Er-Sf_synthetic   
636  GAGGTTAGC  Er-Of-Sr-Kr_synthetic   

                                              Sequence Element_id_simplified  \
0    AGCTACGATTAGCATCCCGTAGCTAGCGGCCCCACCCCGTAGCTAC...                  okeS   
1             AGCTACGTGACCTTGAACGTAGCTACGATTAGCATCCCGT                    eo   
2    AGCTACGATTAGCATCCCGTAGCTACGAAACAATGAGCGTAGCTAC...                  osKe   
3    AGCTACGGGGTGGGGCCGCTAGCTACGTGACCTTGAACGTAGCTAC...                  KesO   
4    AGCTAGCGGCCCCACCCCGTAGCTACGCTCATTGTTTCGTAGCTAC...                  kSEo   
..                                                 ...                   ...   
632  AGCTACGAAACAATGAGCGTAGCTACGGGGTGGGGCCGCTAGCTAC...                  sKEO   
633  AGCTACGAAACAATGAGCGTAGCTACGTTCAAGGTCACGTAGCTAC...                   sEK   
634  AGCTAGCGGCCCCACCCCGTAGCTACGCTCATTGTTTCGTAGCTAC...                   kSo   
635           AGCTACGTGACCTTGAACGTAGCTACGCTCATTGTTTCGT                    eS   
636  AGCTACGTGACCTTGAACGTAGCTACGGGATGCTAATCGTAGCTAC...                  eOsk   

    Class  CRE_normalized_mean O_presence S_presence K_presence E_presence  \
0    4mer             4.589322       True       True       True       True   
1    2mer             1.008053       True      False      False       True   
2    4mer            10.712129       True       True       True       True   
3    4mer             3.453898       True       True       True       True   
4    4mer             3.939580       True       True       True       True   
..    ...                  ...        ...        ...        ...        ...   
632  4mer             6.241055       True       True       True       True   
633  3mer             3.106084      False       True       True       True   
634  3mer             2.145780       True       True       True      False   
635  2mer             1.003107      False       True      False       True   
636  4mer             4.307021       True       True       True       True   

     ... Position.3_K Position.3_E Position.2_O Position.2_S Position.2_K  \
0    ...        False         True        False        False         True   
1    ...        False         True        False        False        False   
2    ...         True        False        False         True        False   
3    ...        False        False        False        False        False   
4    ...        False         True        False         True        False   
..   ...          ...          ...          ...          ...          ...   
632  ...        False         True        False        False         True   
633  ...        False         True        False         True        False   
634  ...        False        False        False        False         True   
635  ...        False         True        False        False        False   
636  ...        False        False         True        False        False   

    Position.2_E Position.1_O Position.1_S Position.1_K Position.1_E  
0          False         True        False        False        False  
1          False        False        False        False        False  
2          False         True        False        False        False  
3           True        False        False         True        False  
4          False        False        False         True        False  
..           ...          ...          ...          ...          ...  
632        False        False         True        False        False  
633        False        False        False        False        False  
634        False        False        False        Fa

In [6]:
# Add function registry for normalization
data["log_CRE_normalized_mean"] = np.log2(data["CRE_normalized_mean"])

In [7]:
# 
nan_mask = np.isnan(data["log_CRE_normalized_mean"])
data = data[~nan_mask]
data

Barcode             Element_id  \
0    AAACACTTG  Or-Kr-Er-Sf_synthetic   
1    AAACCAAGT        Er-Or_synthetic   
2    AAACCACAA  Or-Sr-Kf-Er_synthetic   
3    AAACCAGAC  Kf-Er-Sr-Of_synthetic   
4    AAACCAGTG  Kr-Sf-Ef-Or_synthetic   
..         ...                    ...   
632  CTCCTAAAG  Sr-Kf-Ef-Of_synthetic   
633  CTGGGTACC     Sr-Ef-Kf_synthetic   
634  CTTCGTCCC     Kr-Sf-Or_synthetic   
635  GAGAGCGGA        Er-Sf_synthetic   
636  GAGGTTAGC  Er-Of-Sr-Kr_synthetic   

                                              Sequence Element_id_simplified  \
0    AGCTACGATTAGCATCCCGTAGCTAGCGGCCCCACCCCGTAGCTAC...                  okeS   
1             AGCTACGTGACCTTGAACGTAGCTACGATTAGCATCCCGT                    eo   
2    AGCTACGATTAGCATCCCGTAGCTACGAAACAATGAGCGTAGCTAC...                  osKe   
3    AGCTACGGGGTGGGGCCGCTAGCTACGTGACCTTGAACGTAGCTAC...                  KesO   
4    AGCTAGCGGCCCCACCCCGTAGCTACGCTCATTGTTTCGTAGCTAC...                  kSEo   
..                                                 ...                   ...   
632  AGCTACGAAACAATGAGCGTAGCTACGGGGTGGGGCCGCTAGCTAC...                  sKEO   
633  AGCTACGAAACAATGAGCGTAGCTACGTTCAAGGTCACGTAGCTAC...                   sEK   
634  AGCTAGCGGCCCCACCCCGTAGCTACGCTCATTGTTTCGTAGCTAC...                   kSo   
635           AGCTACGTGACCTTGAACGTAGCTACGCTCATTGTTTCGT                    eS   
636  AGCTACGTGACCTTGAACGTAGCTACGGGATGCTAATCGTAGCTAC...                  eOsk   

    Class  CRE_normalized_mean O_presence S_presence K_presence E_presence  \
0    4mer             4.589322       True       True       True       True   
1    2mer             1.008053       True      False      False       True   
2    4mer            10.712129       True       True       True       True   
3    4mer             3.453898       True       True       True       True   
4    4mer             3.939580       True       True       True       True   
..    ...                  ...        ...        ...        ...        ...   
632  4mer             6.241055       True       True       True       True   
633  3mer             3.106084      False       True       True       True   
634  3mer             2.145780       True       True       True      False   
635  2mer             1.003107      False       True      False       True   
636  4mer             4.307021       True       True       True       True   

     ... Position.3_E Position.2_O Position.2_S Position.2_K Position.2_E  \
0    ...         True        False        False         True        False   
1    ...         True        False        False        False        False   
2    ...        False        False         True        False        False   
3    ...        False        False        False        False         True   
4    ...         True        False         True        False        False   
..   ...          ...          ...          ...          ...          ...   
632  ...         True        False        False         True        False   
633  ...         True        False         True        False        False   
634  ...        False        False        False         True        False   
635  ...         True        False        False        False        False   
636  ...        False         True        False        False        False   

    Position.1_O Position.1_S Position.1_K Position.1_E  \
0           True        False        False        False   
1          False        False        False        False   
2           True        False        False        False   
3          False        False         True        False   
4          False        False         True        False   
..           ...          ...          ...          ...   
632        False         True        False        False   
633        False        False        False        False   
634        False        False        False        False   
635        False        False        False        False   
636        False        False        False

In [8]:
seqs = data["Sequence"].values
patterns = dict(
    sox2 = ["GCTCATTGTTTC"],
    pou5f1 = ["GGGATGCTAATC"],
    esrrb = ["GTTCAAGGTCAC"],
    klf4 = ["GGGGTGGGGCCG"],
)
include_rc = True

In [9]:
# Encode
ohe_in_seqs_tensor, tfs = tfbs_encode(
    seqs=seqs,
    patterns=patterns,
    include_rc=include_rc,
    max_length=80,
    verbose=False,
)

tensor([[[0., 0., 1., 0.],
         [0., 1., 0., 0.],
         [0., 0., 0., 1.],
         [0., 1., 0., 0.],
         [1., 0., 0., 0.],
         [0., 0., 0., 1.],
         [0., 0., 0., 1.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.],
         [0., 0., 0., 1.],
         [0., 0., 0., 1.],
         [0., 1., 0., 0.]]])
tensor(12.)
12
tensor([[[0., 0., 1., 0.],
         [0., 0., 1., 0.],
         [0., 0., 1., 0.],
         [1., 0., 0., 0.],
         [0., 0., 0., 1.],
         [0., 0., 1., 0.],
         [0., 1., 0., 0.],
         [0., 0., 0., 1.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [0., 0., 0., 1.],
         [0., 1., 0., 0.]]])
tensor(12.)
12
tensor([[[0., 0., 1., 0.],
         [0., 0., 0., 1.],
         [0., 0., 0., 1.],
         [0., 1., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.],
         [0., 1., 0., 0.],
         [1., 0., 0., 0.],
         [0., 1., 0.,

In [10]:
import xarray as xr

In [39]:
import seqpro as sp

In [40]:
sp.pad_seqs?

Signature:
sp.pad_seqs(
    seqs: Union[str, List[str], numpy.ndarray[Any, numpy.dtype[Union[numpy.str_, numpy.object_, numpy.bytes_, numpy.uint8]]]],
    pad: Literal['left', 'both', 'right'],
    pad_value: Optional[str] = None,
    length: Optional[int] = None,
    length_axis: Optional[int] = None,
) -> numpy.ndarray[typing.Any, numpy.dtype[typing.Union[numpy.bytes_, numpy.uint8]]]
Docstring:
Pad (or truncate) sequences on either the left, right, or both sides.

Parameters
----------
seqs : Iterable[str]
pad : Literal["left", "both", "right"]
    How to pad. If padding on both sides and an odd amount of padding is needed, 1
    more pad value will be on the right side. Similarly for truncating, if an odd
    amount length needs to be truncated, 1 more character will be truncated from the
    right side.
pad_val : str, optional
    Single character to pad sequences with. Needed for string input. Ignored for OHE
    sequences.
length : int, optional
    Needed for character or OHE ar

In [44]:
sp.ohe(sp.pad_seqs(data["Sequence"], length=80, pad="both", pad_value="N"), sp.alphabets.DNA).transpose(0, 2, 1).shape

/cellar/users/aklie/opt/miniconda3/envs/ml4gland/lib/python3.9/site-packages/seqpro/_utils.py:44: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  return seqs.astype("S")[..., None].view("S1")


(624, 4, 80)

In [150]:
sdata = xr.Dataset({
    "ohe_seq": xr.DataArray(ohe_in_seqs_tensor, dims=["_sequence", "_ohe", "_length"]),
    #"ohe_seq": xr.DataArray(sp.ohe(sp.pad_seqs(data["Sequence"], length=80, pad="both", pad_value="N"), sp.alphabets.DNA).transpose(0, 2, 1), dims=["_sequence", "_ohe", "_length"]),
    "target": xr.DataArray(data["log_CRE_normalized_mean"].values, dims=["_sequence"]),
})
sdata

<xarray.Dataset>
Dimensions:  (_sequence: 624, _ohe: 8, _length: 72)
Dimensions without coordinates: _sequence, _ohe, _length
Data variables:
    ohe_seq  (_sequence, _ohe, _length) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0
    target   (_sequence) float64 2.198 0.01157 3.421 ... 1.102 0.004475 2.107

In [151]:
test_seqs = torch.tensor(sdata["ohe_seq"].isel(_sequence=slice(0, 10)).values, dtype=torch.float32)
test_seqs

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0., 

In [152]:
import seqmodels as sm

In [153]:
sm.CNN?

Init signature:
sm.CNN(
    input_len: int,
    output_dim: Optional[int] = None,
    conv1d_tower_params: Optional[Dict[str, Union[List, str]]] = None,
    dense_tower_params: Optional[Dict[str, Union[List, str]]] = None,
    conv1d_tower_conv_channels: Union[List, str, NoneType] = None,
    conv1d_tower_conv_kernels: Union[List, str, NoneType] = None,
    conv1d_tower_conv_types: Union[List, str, NoneType] = 'conv1d',
    conv1d_tower_conv_strides: Union[List, str, NoneType] = 1,
    conv1d_tower_conv_paddings: Union[List, str, NoneType] = 'valid',
    conv1d_tower_conv_dilations: Union[List, str, NoneType] = 1,
    conv1d_tower_conv_biases: Union[List, str, NoneType] = True,
    conv1d_tower_conv_activations: Union[List, str, NoneType] = 'relu',
    conv1d_tower_pool_types: Union[List, str, NoneType] = 'max',
    conv1d_tower_pool_kernels: Union[List, str, NoneType] = 1,
    conv1d_tower_pool_strides: Union[List, str, NoneType] = None,
    conv1d_tower_pool_paddings: Union[List, str

In [155]:
arch = sm.CNN(
    input_len=72,
    output_dim=1,
    conv1d_tower_conv_channels=[8, 32],
    conv1d_tower_conv_kernels=[8],
    dense_tower_orders = 'linear'

)
arch, arch(test_seqs)

(CNN(
   (conv1d_tower): Tower(
     (blocks): Sequential(
       (conv1dblock_0): Conv1DBlock(
         (layers): Sequential(
           (conv): Conv1d(8, 32, kernel_size=(8,), stride=(1,), padding=valid)
           (act): ReLU()
           (pool): MaxPool1d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
           (norm): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
         )
       )
     )
   )
   (flatten): Flatten(start_dim=1, end_dim=-1)
   (dense_block): Tower(
     (blocks): Sequential(
       (denseblock_0): DenseBlock(
         (layers): Sequential(
           (linear): Linear(in_features=2080, out_features=1, bias=True)
         )
       )
     )
   )
 ),
 tensor([[ 0.2889],
         [ 0.1597],
         [ 0.4054],
         [ 0.3984],
         [-0.9294],
         [ 0.3498],
         [ 0.7634],
         [ 0.7713],
         [ 0.1397],
         [-0.1878]], grad_fn=<AddmmBackward0>))

In [15]:
# Build a simple convolutional model that uses a single wide 1d conv, passes through 4 residual convs
arch = ResidualBind(
    input_len=72,
    output_dim=1,
    input_channels=8
)
arch, arch(ohe_in_seqs_tensor[:10])

(ResidualBind(
   (conv1d_block): Conv1DBlock(
     (layers): Sequential(
       (conv): Conv1d(8, 96, kernel_size=(11,), stride=(1,), padding=valid, bias=False)
       (norm): BatchNorm1d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
       (act): ReLU()
       (dropout): Dropout(p=0.1, inplace=False)
     )
   )
   (res_tower): Residual(
     (wrapped): Tower(
       (blocks): Sequential(
         (conv1dblock_0): Conv1DBlock(
           (layers): Sequential(
             (conv): Conv1d(96, 96, kernel_size=(3,), stride=(1,), padding=same, bias=False)
             (norm): BatchNorm1d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
             (act): ReLU()
             (dropout): Dropout(p=0.1, inplace=False)
           )
         )
         (conv1dblock_1): Conv1DBlock(
           (layers): Sequential(
             (conv): Conv1d(96, 96, kernel_size=(3,), stride=(1,), padding=same, dilation=(2,), bias=False)
             (norm): BatchNorm1d(

# Training module

In [156]:
from seqmodels import Module

In [157]:
import torch

In [158]:
test_dict = {"ohe_seq": torch.tensor(sdata["ohe_seq"].isel(_sequence=slice(0, 10)).values, dtype=torch.float32)}

In [159]:
# Make a module
module = Module(
    arch=arch,
    input_vars=["ohe_seq"],
    output_vars=["output"],
    target_vars=["target"],
    loss_fxn="mse",
    train_metrics_fxn=["r2", "pearson", "spearman"],
    val_metrics_fxn=["r2", "pearson", "spearman"],
    scheduler="reduce_lr_on_plateau",
)
module, module(test_dict).shape

(Module(
   (arch): CNN(
     (conv1d_tower): Tower(
       (blocks): Sequential(
         (conv1dblock_0): Conv1DBlock(
           (layers): Sequential(
             (conv): Conv1d(8, 32, kernel_size=(8,), stride=(1,), padding=valid)
             (act): ReLU()
             (pool): MaxPool1d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
             (norm): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
           )
         )
       )
     )
     (flatten): Flatten(start_dim=1, end_dim=-1)
     (dense_block): Tower(
       (blocks): Sequential(
         (denseblock_0): DenseBlock(
           (layers): Sequential(
             (linear): Linear(in_features=2080, out_features=1, bias=True)
           )
         )
       )
     )
   )
   (loss_fxn): GeneralLoss()
   (train_metrics_fxn): GeneralMetric()
   (val_metrics_fxn): GeneralMetric()
 ),
 torch.Size([10, 1]))

# DataLoaders

In [160]:
# Split into train and validation based on random 50/50
train_idx, val_idx = np.split(np.random.permutation(len(sdata["_sequence"])), [int(0.5 * len(sdata["_sequence"]))])
train_sdata = sdata.isel(_sequence=train_idx)
valid_sdata = sdata.isel(_sequence=val_idx)
train_sdata, valid_sdata

(<xarray.Dataset>
 Dimensions:  (_sequence: 312, _ohe: 8, _length: 72)
 Dimensions without coordinates: _sequence, _ohe, _length
 Data variables:
     ohe_seq  (_sequence, _ohe, _length) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0
     target   (_sequence) float64 2.802 1.468 1.761 1.003 ... 1.602 1.788 3.446,
 <xarray.Dataset>
 Dimensions:  (_sequence: 312, _ohe: 8, _length: 72)
 Dimensions without coordinates: _sequence, _ohe, _length
 Data variables:
     ohe_seq  (_sequence, _ohe, _length) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0
     target   (_sequence) float64 1.995 2.387 1.53 2.726 ... 2.959 2.317 1.624)

In [161]:
train_data = ohe_in_seqs_tensor[train_idx]
valid_sdata = sdata.isel(_sequence=val_idx)
train_sdata, valid_sdata

(<xarray.Dataset>
 Dimensions:  (_sequence: 312, _ohe: 8, _length: 72)
 Dimensions without coordinates: _sequence, _ohe, _length
 Data variables:
     ohe_seq  (_sequence, _ohe, _length) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0
     target   (_sequence) float64 2.802 1.468 1.761 1.003 ... 1.602 1.788 3.446,
 <xarray.Dataset>
 Dimensions:  (_sequence: 312, _ohe: 8, _length: 72)
 Dimensions without coordinates: _sequence, _ohe, _length
 Data variables:
     ohe_seq  (_sequence, _ohe, _length) float32 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0
     target   (_sequence) float64 1.995 2.387 1.53 2.726 ... 2.959 2.317 1.624)

In [162]:
import seqdata as sd

In [163]:
# Train dataloader
train_dl = sd.get_torch_dataloader(
    train_sdata.load(),
    sample_dims="_sequence",
    variables=["ohe_seq", "target"],
    batch_size=32,
    shuffle=True,
    num_workers=0,
    drop_last=True,
    pin_memory=True,
)
batch = next(iter(train_dl))
batch["ohe_seq"].shape, batch["target"].shape

/cellar/users/aklie/opt/miniconda3/envs/ml4gland/lib/python3.9/site-packages/xarray/core/utils.py:494: FutureWarning: The return type of `Dataset.dims` will be changed to return a set of dimension names in future, in order to be more consistent with `DataArray.dims`. To access a mapping from dimension names to lengths, please use `Dataset.sizes`.
  warnings.warn(


(torch.Size([32, 8, 72]), torch.Size([32]))

In [164]:
# Validation dataloader
valid_dl = sd.get_torch_dataloader(
    valid_sdata.load(),
    sample_dims="_sequence",
    variables=["ohe_seq", "target"],
    batch_size=32,
    shuffle=False,
    num_workers=0,
    drop_last=False,
    pin_memory=True,
)
batch = next(iter(valid_dl))
batch["ohe_seq"].shape, batch["target"].shape

(torch.Size([32, 8, 72]), torch.Size([32]))

# Trainer

In [165]:
from pytorch_lightning import Trainer

In [166]:
# Logger
from pytorch_lightning.loggers import CSVLogger
logger = CSVLogger(save_dir="log", name="", version="")

In [167]:
# Add ModelCheckpoint, EarlyStopping and LearningRateMonitor callbacks
from pytorch_lightning.callbacks import ModelCheckpoint, EarlyStopping, LearningRateMonitor
callbacks = [
ModelCheckpoint(
    dirpath=os.path.join(
        logger.save_dir, 
        logger.name, 
        logger.version, 
        "checkpoints"
    ),
    save_top_k=5,
    monitor="val_loss_epoch",
    mode="min",
),
    EarlyStopping(
        monitor="val_loss_epoch",
        patience=10,
        mode="min",
    ),
    LearningRateMonitor(),
]

In [168]:
# Trainer
trainer = Trainer(
    logger=logger,
    callbacks=callbacks,
    max_epochs=100,
    check_val_every_n_epoch=1,
)

/cellar/users/aklie/opt/miniconda3/envs/ml4gland/lib/python3.9/site-packages/lightning_fabric/plugins/environments/slurm.py:165: PossibleUserWarning: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python /cellar/users/aklie/opt/miniconda3/envs/ml4gland/lib ...
  rank_zero_warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


# Fit

In [169]:
# Fit the weigths
trainer.fit(module, train_dl, valid_dl)

You are using a CUDA device ('NVIDIA A30') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
/cellar/users/aklie/opt/miniconda3/envs/ml4gland/lib/python3.9/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:612: UserWarning: Checkpoint directory /cellar/users/aklie/data/datasets/King20_OSKN_MPRA/log/checkpoints exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name              | Type          | Params
----------------------------------------------------
0 | arch              | CNN           | 4.2 K 
1 | loss_fxn          | GeneralLoss   | 0     
2 | train_metrics_fxn | GeneralMetric | 0     
3 | val_metrics_fxn   | GeneralM

Sanity Checking: 0it [00:00, ?it/s]

/cellar/users/aklie/opt/miniconda3/envs/ml4gland/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:430: PossibleUserWarning: The dataloader, val_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 64 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
/cellar/users/aklie/opt/miniconda3/envs/ml4gland/lib/python3.9/site-packages/torchmetrics/utilities/prints.py:43: UserWarning: The variance of predictions or target is close to zero. This can cause instability in Pearson correlationcoefficient, leading to wrong results. Consider re-scaling the input if possible or computing using alarger dtype (currently using torch.float32).
  warnings.warn(*args, **kwargs)  # noqa: B028
/cellar/users/aklie/opt/miniconda3/envs/ml4gland/lib/python3.9/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:430: PossibleUser

Training: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

In [170]:
# Get the best model weights
best_model_path = trainer.checkpoint_callback.best_model_path
copy_path = os.path.join("best_model.ckpt")
os.system(f"cp {best_model_path} {copy_path}")

0

In [171]:
from bin.utils import training_summary

In [172]:
# Plot loss and metric curves
training_summary(logger.save_dir, logger="csv", metrics=["r2", "pearson", "spearman"], save="training_summary.png")

# Performance

In [173]:
from bin.utils import scatter

In [174]:
# Load up the best model
module = Module.load_from_checkpoint("best_model.ckpt", arch=arch).eval().cuda()

In [175]:
# Get predictions and targets as arrays
preds_dict = module.predict({"seq": valid_sdata["ohe_seq"].values.astype("float32")})
preds = preds_dict["output"].cpu().numpy().squeeze()
targets = valid_sdata["target"].values

Predicting on batches:   0%|          | 0/9 [00:00<?, ?it/s]

In [176]:
# Save the predictions
df = pd.DataFrame({
    "target": targets,
    "pred": preds,
})
df.to_csv("val_predictions.csv", index=False)

In [177]:
# Plot a nice blue color
scatter(
    x=targets,
    y=preds,
    c="#4682B4",
    alpha=0.8,
    xlabel="Experimental activity scores",
    ylabel="Predicted activity scores",
    density=True,
    rasterized=True,
    s=5,
    save="val_scatter.png",
)

In [179]:
gen_data = king20("GEN", "./processed/2024_03_10")

Design spreadsheet already exists at ./design.xlsx
Model spreadsheet already exists at ./models.xlsx
Gkmsvm fasta already exists at ./GEN.fasta
mm10 fasta already exists at ./mm10.fa.gz


/cellar/users/aklie/data/datasets/King20_OSKN_MPRA/bin/King20.py:64: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  bc_grouped = merged.groupby("Element_id").agg("mean")


In [183]:
# Encode
ohe_in_seqs_tensor, tfs = tfbs_encode(
    seqs=gen_data["Sequence"].values,
    patterns=patterns,
    include_rc=include_rc,
    max_length=80,
    verbose=False,
)

tensor([[[0., 0., 1., 0.],
         [0., 1., 0., 0.],
         [0., 0., 0., 1.],
         [0., 1., 0., 0.],
         [1., 0., 0., 0.],
         [0., 0., 0., 1.],
         [0., 0., 0., 1.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.],
         [0., 0., 0., 1.],
         [0., 0., 0., 1.],
         [0., 1., 0., 0.]]])
tensor(10.)
12
tensor([[[0., 0., 1., 0.],
         [0., 0., 1., 0.],
         [0., 0., 1., 0.],
         [1., 0., 0., 0.],
         [0., 0., 0., 1.],
         [0., 0., 1., 0.],
         [0., 1., 0., 0.],
         [0., 0., 0., 1.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [0., 0., 0., 1.],
         [0., 1., 0., 0.]]])
tensor(10.)
12
tensor([[[0., 0., 1., 0.],
         [0., 0., 0., 1.],
         [0., 0., 0., 1.],
         [0., 1., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.],
         [0., 1., 0., 0.],
         [1., 0., 0., 0.],
         [0., 1., 0.,

In [181]:
test_sdata = xr.Dataset({
    "ohe_seq": xr.DataArray(sp.ohe(sp.pad_seqs(gen_data["Sequence"], length=80, pad="both", pad_value="N"), sp.alphabets.DNA).transpose(0, 2, 1), dims=["_sequence", "_ohe", "_length"]),
})

/cellar/users/aklie/opt/miniconda3/envs/ml4gland/lib/python3.9/site-packages/seqpro/_utils.py:44: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  return seqs.astype("S")[..., None].view("S1")


In [182]:
# Get predictions and targets as arrays
preds_dict = module.predict({"seq": test_sdata["ohe_seq"].values.astype("float32")})
preds = preds_dict["output"].cpu().numpy().squeeze()

Predicting on batches:   0%|          | 0/12 [00:00<?, ?it/s]

RuntimeError: Given groups=1, weight of size [32, 8, 8], expected input[32, 4, 80] to have 8 channels, but got 4 channels instead